//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineStopRoute
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LineStopRoute.WebService1Soap")]
    public interface WebService1Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDurak_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<LineStopRoute.GetDurak_XMLResponse> GetDurak_XMLAsync(LineStopRoute.GetDurak_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDurak_json", ReplyAction="*")]
        System.Threading.Tasks.Task<LineStopRoute.GetDurak_jsonResponse> GetDurak_jsonAsync(LineStopRoute.GetDurak_jsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGaraj_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<LineStopRoute.GetGaraj_XMLResponse> GetGaraj_XMLAsync(LineStopRoute.GetGaraj_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGaraj_json", ReplyAction="*")]
        System.Threading.Tasks.Task<LineStopRoute.GetGaraj_jsonResponse> GetGaraj_jsonAsync(LineStopRoute.GetGaraj_jsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDurak_XMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDurak_XML", Namespace="http://tempuri.org/", Order=0)]
        public LineStopRoute.GetDurak_XMLRequestBody Body;
        
        public GetDurak_XMLRequest()
        {
        }
        
        public GetDurak_XMLRequest(LineStopRoute.GetDurak_XMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDurak_XMLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DurakKodu;
        
        public GetDurak_XMLRequestBody()
        {
        }
        
        public GetDurak_XMLRequestBody(string DurakKodu)
        {
            this.DurakKodu = DurakKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDurak_XMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDurak_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public LineStopRoute.GetDurak_XMLResponseBody Body;
        
        public GetDurak_XMLResponse()
        {
        }
        
        public GetDurak_XMLResponse(LineStopRoute.GetDurak_XMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDurak_XMLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetDurak_XMLResult;
        
        public GetDurak_XMLResponseBody()
        {
        }
        
        public GetDurak_XMLResponseBody(System.Xml.XmlElement GetDurak_XMLResult)
        {
            this.GetDurak_XMLResult = GetDurak_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDurak_jsonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDurak_json", Namespace="http://tempuri.org/", Order=0)]
        public LineStopRoute.GetDurak_jsonRequestBody Body;
        
        public GetDurak_jsonRequest()
        {
        }
        
        public GetDurak_jsonRequest(LineStopRoute.GetDurak_jsonRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDurak_jsonRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DurakKodu;
        
        public GetDurak_jsonRequestBody()
        {
        }
        
        public GetDurak_jsonRequestBody(string DurakKodu)
        {
            this.DurakKodu = DurakKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDurak_jsonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDurak_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public LineStopRoute.GetDurak_jsonResponseBody Body;
        
        public GetDurak_jsonResponse()
        {
        }
        
        public GetDurak_jsonResponse(LineStopRoute.GetDurak_jsonResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDurak_jsonResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDurak_jsonResult;
        
        public GetDurak_jsonResponseBody()
        {
        }
        
        public GetDurak_jsonResponseBody(string GetDurak_jsonResult)
        {
            this.GetDurak_jsonResult = GetDurak_jsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGaraj_XMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGaraj_XML", Namespace="http://tempuri.org/", Order=0)]
        public LineStopRoute.GetGaraj_XMLRequestBody Body;
        
        public GetGaraj_XMLRequest()
        {
        }
        
        public GetGaraj_XMLRequest(LineStopRoute.GetGaraj_XMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetGaraj_XMLRequestBody
    {
        public GetGaraj_XMLRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGaraj_XMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGaraj_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public LineStopRoute.GetGaraj_XMLResponseBody Body;
        
        public GetGaraj_XMLResponse()
        {
        }
        
        public GetGaraj_XMLResponse(LineStopRoute.GetGaraj_XMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGaraj_XMLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetGaraj_XMLResult;
        
        public GetGaraj_XMLResponseBody()
        {
        }
        
        public GetGaraj_XMLResponseBody(System.Xml.XmlElement GetGaraj_XMLResult)
        {
            this.GetGaraj_XMLResult = GetGaraj_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGaraj_jsonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGaraj_json", Namespace="http://tempuri.org/", Order=0)]
        public LineStopRoute.GetGaraj_jsonRequestBody Body;
        
        public GetGaraj_jsonRequest()
        {
        }
        
        public GetGaraj_jsonRequest(LineStopRoute.GetGaraj_jsonRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetGaraj_jsonRequestBody
    {
        
        public GetGaraj_jsonRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGaraj_jsonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGaraj_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public LineStopRoute.GetGaraj_jsonResponseBody Body;
        
        public GetGaraj_jsonResponse()
        {
        }
        
        public GetGaraj_jsonResponse(LineStopRoute.GetGaraj_jsonResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGaraj_jsonResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGaraj_jsonResult;
        
        public GetGaraj_jsonResponseBody()
        {
        }
        
        public GetGaraj_jsonResponseBody(string GetGaraj_jsonResult)
        {
            this.GetGaraj_jsonResult = GetGaraj_jsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WebService1SoapChannel : LineStopRoute.WebService1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<LineStopRoute.WebService1Soap>, LineStopRoute.WebService1Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebService1SoapClient() : 
                base(WebService1SoapClient.GetDefaultBinding(), WebService1SoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WebService1Soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), WebService1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LineStopRoute.GetDurak_XMLResponse> LineStopRoute.WebService1Soap.GetDurak_XMLAsync(LineStopRoute.GetDurak_XMLRequest request)
        {
            return base.Channel.GetDurak_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<LineStopRoute.GetDurak_XMLResponse> GetDurak_XMLAsync(string DurakKodu)
        {
            LineStopRoute.GetDurak_XMLRequest inValue = new LineStopRoute.GetDurak_XMLRequest();
            inValue.Body = new LineStopRoute.GetDurak_XMLRequestBody();
            inValue.Body.DurakKodu = DurakKodu;
            return ((LineStopRoute.WebService1Soap)(this)).GetDurak_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LineStopRoute.GetDurak_jsonResponse> LineStopRoute.WebService1Soap.GetDurak_jsonAsync(LineStopRoute.GetDurak_jsonRequest request)
        {
            return base.Channel.GetDurak_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<LineStopRoute.GetDurak_jsonResponse> GetDurak_jsonAsync(string DurakKodu)
        {
            LineStopRoute.GetDurak_jsonRequest inValue = new LineStopRoute.GetDurak_jsonRequest();
            inValue.Body = new LineStopRoute.GetDurak_jsonRequestBody();
            inValue.Body.DurakKodu = DurakKodu;
            return ((LineStopRoute.WebService1Soap)(this)).GetDurak_jsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LineStopRoute.GetGaraj_XMLResponse> LineStopRoute.WebService1Soap.GetGaraj_XMLAsync(LineStopRoute.GetGaraj_XMLRequest request)
        {
            return base.Channel.GetGaraj_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<LineStopRoute.GetGaraj_XMLResponse> GetGaraj_XMLAsync()
        {
            LineStopRoute.GetGaraj_XMLRequest inValue = new LineStopRoute.GetGaraj_XMLRequest();
            inValue.Body = new LineStopRoute.GetGaraj_XMLRequestBody();
            return ((LineStopRoute.WebService1Soap)(this)).GetGaraj_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LineStopRoute.GetGaraj_jsonResponse> LineStopRoute.WebService1Soap.GetGaraj_jsonAsync(LineStopRoute.GetGaraj_jsonRequest request)
        {
            return base.Channel.GetGaraj_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<LineStopRoute.GetGaraj_jsonResponse> GetGaraj_jsonAsync()
        {
            LineStopRoute.GetGaraj_jsonRequest inValue = new LineStopRoute.GetGaraj_jsonRequest();
            inValue.Body = new LineStopRoute.GetGaraj_jsonRequestBody();
            return ((LineStopRoute.WebService1Soap)(this)).GetGaraj_jsonAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.ibb.gov.tr/iett/UlasimAnaVeri/HatDurakGuzergah.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WebService1SoapClient.GetBindingForEndpoint(EndpointConfiguration.WebService1Soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WebService1SoapClient.GetEndpointAddress(EndpointConfiguration.WebService1Soap);
        }
        
        public enum EndpointConfiguration
        {
            
            WebService1Soap,
        }
    }
}